name: Docker build

on:
  push:
    branches:
      - main # Указать номер свой ветки


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t happymishka/my-image-name2:latest .

    - name: Push Docker image to Docker hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push happymishka/my-image-name2:latest
