name: Docker build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Docker image tag'
        required: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Build Docker image
      run: docker build -t happymishka/my-image-name2:${{ github.event.inputs.tag }} .

    - name: Push Docker image to Docker hub
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push happymishka/my-image-name2:${{ github.event.inputs.tag }}
